OfficeDev/office-scripts-docs-reference

Issue_Template.md, docs/docs-ref-autogen/excel/excel/excel.application.yml, docs/docs-ref-autogen/excel/excel/excel.bindingcollection.yml, docs/docs-ref-autogen/excel/excel/excel.chart.yml, docs/docs-ref-autogen/excel/excel/excel.chartaxes.yml, docs/docs-ref-autogen/excel/excel/excel.chartcollection.yml, docs/docs-ref-autogen/excel/excel/excel.charttrendlinecollection.yml, docs/docs-ref-autogen/excel/excel/excel.commentcollection.yml, docs/docs-ref-autogen/excel/excel/excel.commentreplycollection.yml, docs/docs-ref-autogen/excel/excel/excel.conditionalformatcollection.yml, docs/docs-ref-autogen/excel/excel/excel.conditionalrangebordercollection.yml, docs/docs-ref-autogen/excel/excel/excel.filter.yml, docs/docs-ref-autogen/excel/excel/excel.pagelayout.yml, docs/docs-ref-autogen/excel/excel/excel.pivotfield.yml, docs/docs-ref-autogen/excel/excel/excel.pivotlayout.yml, docs/docs-ref-autogen/excel/excel/excel.range.yml, docs/docs-ref-autogen/excel/excel/excel.rangeareas.yml, docs/docs-ref-autogen/excel/excel/excel.rangebordercollection.yml, docs/docs-ref-autogen/excel/excel/excel.rangesort.yml, docs/docs-ref-autogen/excel/excel/excel.shape.yml, docs/docs-ref-autogen/excel/excel/excel.shapecollection.yml, docs/docs-ref-autogen/excel/excel/excel.tablesort.yml, docs/docs-ref-autogen/excel/excel/excel.worksheet.yml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/scripts/preprocessor.ts
=> Merge to live!

docs/code-snippets/excel-snippets.yaml, docs/docs-ref-autogen/excel-async/overview.md, docs/docs-ref-autogen/excel/excel/excelscript.range.yml, docs/docs-ref-autogen/excel/excel/excelscript.workbook.yml, docs/docs-ref-autogen/excel/excel/excelscript.worksheet.yml, docs/docs-ref-autogen/excel/overview.md, generate-docs/json/excel/snippets.yaml
This is the reference doc version of https://github.com/OfficeDev/office-scripts-docs/pull/123
=> Adding more basic samples

docs/code-snippets/excel-snippets.yaml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.tablesort.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.topbottomconditionalformat.yml, generate-docs/json/excel/snippets.yaml
Also some minor comment formatting tweaks.
=> Adding a sample Range.setValues using a 2D array

docs/code-snippets/excel-snippets.yaml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, generate-docs/json/excel/snippets.yaml
This PR adds three more samples to the Office Scripts ref docs: `Range.clear`, `Workbook.getWorksheets`, and `Worksheet.setTabColor`.
=> Adding more samples

docs/docfx.json
[Preview site](https://review.docs.microsoft.com/en-us/javascript/api/office-scripts/overview?branch=elizs-l2&view=office-scripts)
=> [Admin] (header) Update L2

.openpublishing.publish.config.json
Attempting to clean up so failing PDF generation no longer attempts to build.
=> [Admin] Fully remove PDF gen

.openpublishing.publish.config.json
=> [Admin] Remove PDF

docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml
This is the same sample from https://github.com/OfficeDev/office-scripts-docs/pull/228
=> Adding data validation sample

docs/docs-ref-autogen/excel/excelscript/excelscript.deleteshiftdirection.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml
* Add DeleteShiftDirection example
* Add description
* Use same sample for Range.delete
* Apply suggestions from code review
Co-authored-by: Alison McKay <almckay@microsoft.com>
* Removing errant files
Co-authored-by: Alison McKay <almckay@microsoft.com>
=> Merge to live

Issue_Template.md, docs/docfx.json
This PR redirects the reference to UserVoice to Microsoft Q&A for feature requests.
=> Remove UserVoice references

docs/docs-ref-autogen/excel/excelscript/excelscript.shape.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml
Added in response to https://github.com/OfficeDev/office-scripts-docs/issues/263
=> [Shapes] Add Shape.getImage sample

docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml
We had some samples that highlighted these APIs, so I ported them to the reference docs.
=> [samples] (getHyperlink, addImage) Adding some samples from the office-scripts-docs repo

generate-docs/tools/readme.md
There are some quality refinements I'd like to do before integrating this into the GenerateDocs script. I also have the goal of writing an Office Script to help parse the content.
=> Adding readme for coverage tester

docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationtype.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml
=> [samples] (DataValidation) Add sample to show how to use DataValidationType

docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.chartplotby.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.chartseries.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml
=> [samples] (Charts) Adding Chart and ChartSeries samples

docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/json/excel/ExcelScript.api.json, generate-docs/script-inputs/excel.d.ts
=> [chart] Fix Chart.getImage typo

docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeborder.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangefill.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeformat.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
Adding more samples to the highly visited Range page (and some related pages).
=> [samples] (Range) More range samples

docs/docs-ref-autogen/excel/excelscript/excelscript.keyboarddirection.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheetpositiontype.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
* Adding relative positioning samples
* Running GenerateDocs
* Feedback
=> [admin] Publish

docs/docs-ref-autogen/excel/excelscript/excelscript.rangecopytype.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
Giving this enum a sample for usage context.
=> [excel] (Range) Adding RangeCopyType sample

docs/docs-ref-autogen/excel/excelscript/excelscript.pivottable.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
Adding a couple samples around creating PivotTables. These effectively replicate the UX flow of creating a PivotTable on a new worksheet or an existing worksheet.
=> [excel] (PivotTables) Adding basic PivotTable samples

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformatcolorcriteriontype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformattype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaltopbottomrule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.customconditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.topbottomconditionalformat.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds a couple sample to parts of the conditional formatting reference. Some samples (or pieces of samples) are repeated to help with discoverability depending on where the reader enters the docs.
=> [excel] (Conditional Formatting) Add more samples for Conditional Formatting

docs/docs-ref-autogen/excel/excelscript/excelscript.clearapplyto.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.searchcriteria.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.searchdirection.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv, generate-docs/tools/coverage-tester.ts
This PR creates samples for the two enums in the title (and adds them to a couple more relevant places).
It also removes a chatty log statement from the coverage tool.
=> [excel] (Range) Adding samples for ClearApplyTo and SearchDirection

docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/json/excel/ExcelScript.api.json, generate-docs/script-inputs/excel.d.ts, generate-docs/tools/API Coverage Report.csv
This should just be text fixes that have been approved in other threads.
=> Update type definitions

docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfield.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfilters.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivothierarchy.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivottable.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotvaluefilter.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.valuefiltercondition.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
A recent [Stack Overflow post](https://stackoverflow.com/questions/70946084/pivot-table-filtering-office-scripts/70950721#70950721) identified a gap in sample coverage around PivotFilters. This PR adds a few samples to that area.
=> [samples] (PivotTable) Add PivotHierarchy and PivotFilter samples

docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangefill.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/package-lock.json, generate-docs/scripts/package-lock.json, generate-docs/tools/API Coverage Report.csv, generate-docs/tools/package-lock.json
These samples target commonly recorded actions that didn't already have sample code.
=> [Range] Adding samples to common Range methods

docs/docs-ref-autogen/excel/excelscript/excelscript.filter.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.replacecriteria.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
Requests for these samples came from the anonymous comments left on individual reference doc pages.
=> [Excel] (Range) Samples for ReplaceCriteria and number format

docs/docs-ref-autogen/excel/excelscript/excelscript.filter.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filteroperator.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
These samples were requested through verbatims left with page feedback.
=> [Excel] (Table) Add FilterOperator samples

docs/docs-ref-autogen/excel/excelscript/excelscript.rangeareas.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangefont.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.specialcelltype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.specialcellvaluetype.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
These samples are based on anonymous feedback through the reference documentation pages. There were requests for the aforementioned two interfaces in particular. I also added a couple other samples that were made from easy modifications.
=> [excel] (Range) Adding RangeAreas and RangeFont samples

docs/docs-ref-autogen/excel/excelscript/excelscript.autofilter.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filtercriteria.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filteron.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
Based on an anonymous comment left on the doc pages, we're adding a couple samples around the AutoFilter object.
=> [excel] (Table, Worksheet) Add autoFilter samples

docs/docs-ref-autogen/excel/excelscript/excelscript.pivottablestyle.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.slicerstyle.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.tablestyle.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.timelinestyle.yml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/json/excel/ExcelScript.api.json, generate-docs/script-inputs/excel.d.ts
=> [excel] (Styles) Updating *Style setName text

docs/docs-ref-autogen/excel/excelscript/excelscript.documentproperties.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
This is based on a customer verbatim that indicated confusion about accessing these properties.
=> [excel] (Workbook) Adding a basic DocumentProperties sample

docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfilters.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotlabelfilter.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
As part of an investigation around PivotLabelFilters, I made this script.  Figured it should become a sample.
=> [excel] (PivotTables) Adding PivotLabelFilter sample

docs/docs-ref-autogen/excel/excelscript/excelscript.aggregationfunction.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datapivothierarchy.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangevaluetype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.sheetvisibility.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds samples to AggregationFunction, SheetVisibility, and RangeValueType. These were the highest viewership enum pages without samples. The samples were also added to the methods that use those enums.
=> [excel] (Range, PivotTables, Worksheets) Adding samples to popular enum pages

docs/docs-ref-autogen/excel/excelscript/excelscript.borderindex.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.borderlinestyle.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.borderweight.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.calculationmode.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datefiltercondition.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filterdatetime.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filterdatetimespecificity.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.horizontalalignment.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.labelfiltercondition.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.nameditem.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.nameditemtype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotdatefilter.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfilters.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeborder.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.sortfield.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.sorton.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds samples targeting enum pages with higher viewership. These include NamedItemType, BorderLineStyle, LabelFilterCondition, CalculationMode, HorizontalAlignment, FilterDatetimeSpecificity, BorderIndex, and BorderWeight.
=> [excel] Adding more enum samples

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalcellvalueoperator.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalcellvaluerule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaltextcomparisonrule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaltextoperator.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.textconditionalformat.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/json/excel/snippets.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds one sample to a few relevant places in the docs.
=> [excel] (Conditional Formatting) Adding a TextConditionalFormat sample

Contributing.md, README.md
[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: …
=> [BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

docs/docs-ref-autogen/excel/excelscript/excelscript.basicdatavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationalertstyle.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationerroralert.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationrule.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv, generate-docs/tools/package-lock.json
This PR adds a sample to a few places in the ref docs. The sample shows how to set a data validation rule to enforce positive number values only.
=> [range] (Data Validation) Adding another Data Validation sample

docs/docs-ref-autogen/excel/excelscript/excelscript.application.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.calculationtype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.groupoption.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pagelayout.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pictureformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.printorder.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.shape.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.shapeautosize.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.textframe.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds targeted samples for the following enums.
- CalculationType
- GroupOption
- PictureFormat
- PrintOrder
- ShapeAutoSize
=> [excel] (Settings, Shape, Range) Adding samples

docs/docs-ref-autogen/excel/excelscript/excelscript.commentmention.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.commentrichcontent.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.contenttype.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds a sample that shows how to add an at-mention. It also fixes an implicit-any bug in an older sample.
=> [excel] (Comments) Adding a sample for ContentType

docs/docs-ref-autogen/excel/excelscript/excelscript.placement.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.shape.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/script-inputs/excel.d.ts, generate-docs/tools/API Coverage Report.csv
Fixes #229. It also adds a sample to showcase how that enum works.
=> [excel] (Shapes) Adding Placement sample and fixing description

docs/docs-ref-autogen/excel/excelscript/excelscript.chartseriesby.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds a simple sample showing how to use the `ChartSeriesBy` enum.
=> [excel] (Chart) Adding ChartSeriesBy sample

docs/docs-ref-autogen/excel/excelscript/excelscript.builtinstyle.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filterpivothierarchy.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.image.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.imagefittingmode.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivothierarchy.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeareas.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rowcolumnpivothierarchy.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/script-inputs/excel.d.ts, generate-docs/tools/API Coverage Report.csv
This PR adds two samples, one for each enum mentioned in the title. It also cleans up the IntelliSense file a bit.
=> [excel] (Range, Chart) Adding samples for BuiltInStyle and ImageFittingMode

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformatpresetcriterion.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalpresetcriteriarule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationoperator.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.presetcriteriaconditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.verticalalignment.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR includes three samples for ConditionalFormatPresetCriterion, DataValidationOperator, and VerticalAlignment.
=> [excel] (Formatting, Data Validation) Adding more enum-based samples

docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfield.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfiltertype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotlayout.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotlayouttype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivottable.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR gives samples to the PivotFilterType and PivotLayoutType enums.
=> [excel] (PivotTable) Adding PivotTable samples

docs/docs-ref-autogen/excel/excelscript/excelscript.application.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.calculationstate.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaldatabarrule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformatruletype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.databarconditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.documentproperties.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.documentpropertytype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotlayout.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.subtotallocationtype.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds a handful of samples around the aforementioned areas. There are only 4 new samples total. Some are duplicated for different API areas.
=> [excel] (Formatting, Workbook) Add samples for data bars, custom properties, and calculation state

docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.chartseries.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/api-extractor-inputs-excel/tsdoc-metadata.json, generate-docs/package-lock.json, generate-docs/package.json, generate-docs/tools/API Coverage Report.csv
This PR adds a simple sample around ChartSeries. It also updates the RushStack tooling to ensure the latest versions work.
=> [excel] (Charts) Add ChartSeries sample

docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.tablecolumn.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
Based on https://github.com/OfficeDev/office-scripts-docs/issues/581.
This PR adds a couple samples around adding TableColumns.
=> [excel] (Table) Adding TableColumn samples

docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeview.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
The RangeView samples were using the parent Range, instead of the filtered, visible Range.
=> [excel] (Range) Fixing RangeView sample

docs/docs-ref-autogen/excel/excelscript/excelscript.charterrorbarstype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.chartseries.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds a simple sample showing how to add error bars to a chart series.
=> [excel] (Charts) ChartErrorBars sample

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformaticonruletype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaliconcriterion.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaliconcriterionoperator.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.iconset.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.iconsetconditionalformat.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
This PR adds a sample to show how to use icon set conditional formatting. This one sample is applied to several places in the documentation.
=> [excel] (Conditional Formatting) Add icon set conditional formatting sample

docs/docs-ref-autogen/excel/excelscript/excelscript.datapivothierarchy.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotfield.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivottable.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rowcolumnpivothierarchy.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
Partially inspired by [this Stack Overflow post](https://stackoverflow.com/questions/75815707/office-scripts-sorting-a-pivot-table), this PR adds a sample showing how to sort a PivotTable. This same sample is applied to a few relevant APIs.
=> [excel] (PivotTable) Adding PivotTable sorting sample

docs/docs-ref-autogen/excel/excelscript/excelscript.datetimedatavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datetimeformatinfo.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangesort.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.sortfield.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.textrange.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
Adding samples for range sorting, shape text, date-based data validation, and date/time settings.
=> [excel] (Data Validation, Settings, Shapes, Sort)

docs/docs-ref-autogen/excel/excelscript/excelscript.chartseries.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pivotlayout.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.rangeformat.yml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/script-inputs/excel.d.ts
This PR removes some bad characters and cleans up get/set wording.
=> [excel] Updating reference docs to match latest IntelliSense

docs/docs-ref-autogen/excel/excelscript/excelscript.pagelayout.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pageorientation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.papertype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/tools/API Coverage Report.csv
Someone left a comment requesting more samples around the PageLayout interface. This PR aims to fill that gap.
=> [excel] (PageLayout) Adding some PageLayout samples

docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationprompt.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
This addition is based on customer feedback that sample coverage needed here.
=> [excel] (Data Validation) Adding a data validation prompt sample

docs/docfx.json
Do suggest a more appropriate URL if you have one.
=> Fix broken product feedback link

docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationrule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.listdatavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.tablecolumn.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
This PR adds several samples to high-traffic pages.
=> [excel] (Table, Data Validation) Add table and list validation samples

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionaldatabarrule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformatruletype.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.databarconditionalformat.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
This PR adds a conditional formatting sample and fixes a typo.
=> [excel] (Formatting) Add top/bottom conditional formatting sample

docs/docs-ref-autogen/excel/excelscript/excelscript.rangehyperlink.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
=> [excel] (Range) Add sample for RangeHyperlink.documentReference

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalrangefill.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalrangefont.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalrangeformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.filterpivothierarchy.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
These samples address some gaps reported by customers through the verbatims left on the doc pages.
=> [excel] (Range, PivotTable) Add FilterPivotHierarchy and ConditionalFormat samples

docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, generate-docs/api-extractor-inputs-excel/excel.d.ts, generate-docs/script-inputs/excel.d.ts
Fixes https://github.com/OfficeDev/office-scripts-docs/issues/720.
=> [excel] (Data Connections) Clarify refresh data connections behavior

docs/docfx.json
products contains office-excel which falls under m365
=> Fix build suggestion

docs/docs-ref-autogen/excel/excelscript/excelscript.customdatavalidation.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationrule.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
A customer requested a sample for this API. Here it is!
=> [excel] (Data Validation) Add CustomDataValidation sample

docs/docs-ref-autogen/excel/excelscript/excelscript.linkedworkbook.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.tablecolumn.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.workbook.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv, generate-docs/scripts/package-lock.json
This PR adds three samples, as per the title. It also runs `npm audit fix` on the build scripts.
=> [excel] (Table, Workbook) Add Table and LinekdWorkbook samples

docs/docs-ref-autogen/excel/excelscript/excelscript.alloweditrangeoptions.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pagelayout.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.pagelayoutzoomoptions.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheetprotection.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
This PR adds a couple samples to pages with relatively high page views that didn't have other samples.
=> [excel] (Worksheet) Adding edit range and page zoom samples

docs/docs-ref-autogen/excel/excelscript/excelscript.conditionalformatrule.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.customconditionalformat.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml, docs/docs-ref-autogen/excel/excelscript/excelscript.worksheetsearchcriteria.yml, docs/sample-scripts/excel-scripts.yaml, generate-docs/API Coverage Report.csv
This PR expands a couple existing samples to cover additional API surfaces.
=> [excel] (Formatting, Worksheet) Add search and custom format samples

Contributing.md
Matching some of the edits in this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4730
=> [admin] (Contributing) Minor edits to contributor file

generate-docs/package-lock.json, generate-docs/package.json, generate-docs/scripts/package-lock.json, generate-docs/scripts/postprocessor.ts
This is the same change as https://github.com/OfficeDev/office-js-docs-reference/pull/2168.
=> [all] (Tools) Add blank parameter description protection to postprocessor

docs/docfx.json
Update to align with current Learn standards.
=> [admin] (metadata) Change autogened pages to generated-reference ms.topic

docs/includes/officescript-preview.md, generate-docs/api-extractor-inputs-officescript-release/officescript.d.ts, generate-docs/office-scripts-link-config.json, generate-docs/package-lock.json, generate-docs/package.json, generate-docs/scripts/postprocessor.ts
This also fixes the inconsistent newline bug.
=> [scripts] Update to latest versioned-d.ts-tools
